### ISSUE TITLE
LLGfx and Game Framework

### ISSUE THREAD

**Issue by amerkoleci** [tgjones/OpenSAGE#2]
Hi,
Excellent work on this OpenSage port, any possibility to release the Graphics LLGfx and the game framework as separated libraries?

Probably some user will benefit of it.
Thanks

**Comment by tgjones** [comment]
> Excellent work on this OpenSage port

Thanks :)

> any possibility to release the Graphics LLGfx and the game framework as separated libraries?

At the moment, no plans to release LLGfx or the game framework separately - I want the freedom to develop them as necessary for OpenSAGE, and I'd rather not have the overhead of handling them as a separately versioned library. The game framework in particular is likely to become quite specific to OpenSAGE's needs.

Who knows, in the future, if and when things stabilise, it might be a good idea to extract them, but I think now is too soon.
