### ISSUE TITLE
OpenZH.DataViewer.Windows doesn't build because of a missing shader include

### ISSUE THREAD

**Issue by paavohuhtala** [tgjones/OpenSAGE#3]
When trying to build the project, `OpenZH.DataViewer.Windows` doesn't compile because of a shader compilation error.

`SpritePS.hlsl` and `SpriteVS.hlsl` include a file called `Sprite.hlsli`, which is not present in the current master. It seems to have been removed (or renamed to `Particle.hlsli`) in the commit d94eda7f5744c4eef867bb7297debb9b7c0c8c92.

**Comment by tgjones** [comment]
Thanks - fixed.
