### ISSUE TITLE
Unit tests use hard coded paths

### ISSUE THREAD

**Issue by paavohuhtala** [tgjones/OpenSAGE#4]
_You are most likely already aware of this, but I think it's a good idea to write it down regardless._

The tests use hard coded paths to game files, which makes it hard to run them portably. Most tests seem to use `InstalledFilesTestData`, but some other tests (such as the `BigArchiveTests`) use their own paths.

There are a couple of ways to solve this.

The easiest to implement solution would be to have a configuration file which a developer would enter the path[s] to the game installation folder[s].

From developer experience perspective an even better solution would be to automatically detect where the game is installed. (Much) further down the line, the same logic could be used for the game itself. 

There are at least 3 different editions (original, The First Decade and Origin) of the game, which might require different approaches. I have the Origin copy, and having done some preliminary Windows registry searching and `%appdata%` grepping I couldn't find any non-machine specific references to the game installation path. There must be a way to do this, but I haven't found it yet. :)

**Comment by feliwir** [comment]
You forgot all other SAGE Games, like Battle for Middleearth (I, II and ROTWK) :)

**Comment by tgjones** [comment]
@paavohuhtala I was aware of this, but thank you for writing it down, and for researching whether there was an easy place (i.e. Windows registry) to look to find the installation paths. I'd wondered about the registry, but hadn't looked at it yet.

I'll find some time to investigate this more.

**Comment by paavohuhtala** [comment]
I fired up [RegScanner](http://www.nirsoft.net/utils/regscanner.html) and managed to find the right registry keys in about 5 seconds. 😅 I would have found these sooner if I'd known that [64-bit Windows segregates data](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724072(v=vs.85).aspx) from 32-bit applications into their own registry, which you can't access with the regular regedit. Luckily RegScanner could see both types of entries.

Base directory, containing base game, ZH and launcher:
`HKLM\SOFTWARE\EA Games\Command and Conquer Generals Zero Hour\Install Dir`

Base game:
`HKEY_LOCAL_MACHINE\SOFTWARE\Electronic Arts\EA Games\Generals\InstallPath`

Zero Hour:
`HKEY_LOCAL_MACHINE\SOFTWARE\Electronic Arts\EA Games\Command and Conquer Generals Zero Hour\InstallPath`

These should work for at least the Origin version, and probably other versions too. I'm about 500 kilometers away from my original CD copy right now, so I can't confirm that.
