### ISSUE TITLE
ZL5 compression

### ISSUE THREAD

**Issue by OmniBlade** [tgjones/OpenSAGE#7]
I believe (based on imports in the Mac version of ZH) that ZL5 is decompressed with zlib uncompress.

**Comment by feliwir** [comment]
Where is ZL5 used? I don't know of a format like that used for BFME :D

**Comment by OmniBlade** [comment]
According to the comments in https://github.com/tgjones/OpenSAGE/blob/master/src/OpenSage.Game/Data/Map/MapFile.cs its seen in a single Generals map, probably one of the earliest maps written. ZH at least also supports a number of other compression schemes, but only RefPack is actually used so that is all I've implemented so far for Thyme.

**Comment by tgjones** [comment]
@OmniBlade thanks for the tip! I probably should have guessed that ZL might stand for zlib. I’ll try this out and see how it goes. As you noted, it’s only used by one map, but it would be nice for completeness to support it.

**Comment by tgjones** [comment]
Implemented in 75cbd222d6f83a51340b5dc029a6833e6aef06d9
